name: Grab The Server
on:
  workflow_dispatch:

jobs:
  build:
    name: setup_and_run
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run_script
        run: bash install-ygg-ssh-env.sh
        env:
          YGGCONFDATA: ${{ secrets.YGGCONFDATA }}
          PUBKEY: ${{ secrets.PUBKEY }}
      - name: sleep
        run: sleep 5.5h
